# Generated by Django 3.2.18 on 2023-03-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_comments_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='decription',
            field=models.TextField(),
        ),
    ]
