# Generated by Django 3.2.18 on 2023-03-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_decription_listing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='listings/'),
        ),
    ]
