# Generated by Django 3.2.18 on 2023-04-04 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_soled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soled',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='item', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='soled',
            name='soled_price',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='auctions.bid'),
        ),
    ]
