# Generated by Django 3.2.18 on 2023-04-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20230404_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
