# Generated by Django 4.2 on 2023-04-12 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soled',
            name='listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='soled',
            name='soled_price',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='auctions.bid'),
        ),
    ]
